version: "3"
services:
  nginx:
    image: nginx
    ports:
      - "8080:8080"
    networks:
      - deploymentNetwork    
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
    restart: always  
  app1:
    image: ayadinou/bookstore:${IMAGE_NAME}
    ports:
      - "5001:8080"
    networks:
      - deploymentNetwork
    depends_on:
      - mysqldb
    restart: always
    
  app2:
    image: ayadinou/bookstore:${IMAGE_NAME}
    ports:
      - "5002:8080"
    networks:
      - deploymentNetwork
    depends_on:
      - mysqldb
    restart: always

  mysqldb:
    image: mysql
    ports:
      - "3307:3306"
    networks:
      - deploymentNetwork
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bookstore
      - MYSQL_USER=ayadinouDB
      - MYSQL_PASSWORD=ayadinou1601

    volumes:
      - /var/lib/docker/volumes/mysql-volume/_data:/var/lib/mysql
      - ./script.sql:/docker-entrypoint-initdb.d/schema.sql

    restart: always

networks:
  deploymentNetwork: 
 
